### ISSUE TITLE
have to reload polybar after login

### ISSUE THREAD

**Issue by IIIProphetIII** [odilonscoelho/taskbar#3]
Everytime I login to bspwm,the module says`/bin/sh:line 1:taskbar: command not found`.After reload polybar,it runs fine.I added `sleep 5` before starting polybar,but it didn't fix this.
bspwmrc
```
#taskbar
/home/toor/Software/taskbar/taskbar start &
# polybar
/home/toor/.config/polybar/launch.sh --docky &
```
$Path
```
/home/toor/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/toor/Software/taskbar
```

**Comment by odilonscoelho** [comment]
Hi, today I updated how it imports the settings, you can test if this solved this problem, if not, please provide more details on how is the polybar configuration file where the modules are, but I believe that after today's correction will no longer have this problem.

**Comment by odilonscoelho** [comment]
> Everytime I login to bspwm,the module says`/bin/sh:line 1:taskbar: command not found`.After reload polybar,it runs fine.I added `sleep 5` before starting polybar,but it didn't fix this.
> bspwmrc
> 
> ```
> #taskbar
> /home/toor/Software/taskbar/taskbar start &
> # polybar
> /home/toor/.config/polybar/launch.sh --docky &
> ```
> 
> $Path
> 
> ```
> /home/toor/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/toor/Software/taskbar
> ```

Hi, today I updated how it imports the settings, you can test if this solved this problem, if not, please provide more details on how is the polybar configuration file where the modules are, but I believe that after today's correction will no longer have this problem.

**Comment by IIIProphetIII** [comment]
i figure out where i go wrong.
the configure function in `taskbar: echo "# path para taskbar\nPATH=\$PATH:$PWD" >> $HOME/.zshrc` doesn't work.
when executing bspwmrc,the $PATH is
`
/home/toor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
`
so `/home/toor/Software/taskbar` is not avaliable,meaning that taskbar won't start.

And what does `declare -x path_proj=/path` in EN version `README,md` mean?Do i add it to taskbar file? but it doesn't seem to be refered anyway.
Original `README.md` is very different from EN version, which is rather confusing.

Anyway,after adding all the 4 files to `.local/bin/`, it works perfectly.
